PackageIdentifier: Bytifi.Bytifi
PackageVersion: 0.1.1
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.17763.0
Installers:
  - Architecture: x64
    InstallerType: portable
    InstallerUrl: https://github.com/jpwcguy/Bytifi/releases/download/v0.1.1/bytifi.exe
    InstallerSha256: 106963FA3745417B9E93BCF8E1F4FF6B86A0E52C97EE3EFE772601856F5A45C9
    Commands:
      - bytifi
ManifestType: installer
ManifestVersion: 1.6.0
